security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\Utilisateur:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        # Désactive la sécurité pour le profiler et les assets
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall principal pour gérer la connexion
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_home
            logout:
                path: app_logout
                target : app_login
                # Redirection après la déconnexion (facultatif)
                # target: app_any_route


    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/inscription$, roles: PUBLIC_ACCESS }

        - { path: ^/livre/new, roles: ROLE_ADMIN }
        - { path: ^/livre/edit, roles: ROLE_ADMIN }
        - { path: ^/livre/delete, roles: ROLE_ADMIN }

        - { path: ^/auteur/new, roles: ROLE_ADMIN }
        - { path: ^/auteur/edit, roles: ROLE_ADMIN }
        - { path: ^/auteur/delete, roles: ROLE_ADMIN }
        - { path: ^/genre/new, roles: ROLE_ADMIN }
        - { path: ^/genre/edit, roles: ROLE_ADMIN }
        - { path: ^/genre/delete, roles: ROLE_ADMIN }

        - { path: ^/, roles: ROLE_USER }
